version: '3'

services:
  postgres:
    image: postgres
    environment:
      POSTGRES_DB: server_001
      POSTGRES_USER: server_001
      POSTGRES_PASSWORD: server_001
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  django:
    build:
      context: .
      dockerfile: Dockerfile  # Assuming your Dockerfile is in the same directory
    depends_on:
      - postgres
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: ["python", "/app/manage.py", "runserver", "0.0.0.0:8000"]
    networks:
      - default

volumes:
  postgres_data:

networks:
  default:
