version: '3'

services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: server_002
      POSTGRES_USER: server_002
      POSTGRES_PASSWORD: server_002
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend-network

  django:
    build:
      context: .
      dockerfile: Dockerfile  # Assuming your Dockerfile is in the same directory
    depends_on:
      - postgres
    ports:
      - "8001:8000"
    volumes:
      - .:/app
    command: ["python", "/app/manage.py", "runserver", "0.0.0.0:8000"]
    networks:
      - backend-network

volumes:
  postgres_data:

networks:
  backend-network:
