# Generated by Django 4.2.7 on 2023-11-08 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stateapi', '0003_city'),
    ]

    operations = [
        migrations.DeleteModel(
            name='City',
        ),
    ]
